version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: stratos_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - ../data:/data
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:15
    container_name: stratos_postgres
    environment:
      POSTGRES_DB: stratos
      POSTGRES_USER: stratos
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - ../pgdata:/var/lib/postgresql/data
